public enum EventType
{ 
    OnPerkChanged,
    OnAddLevel,
    OnGameOver,
    OnGameWin,
    OnEnemyKilled,
    OnAdFinished,
    MoveJoystick,
    OpenBuildMenu,
    PlaceBuilding,
    ZoomCamera,
    KillFirstEnemy,
    ActivateShield,
    FirstGoldCatched,
    Survive,
    OnBannerAdShown,
    OnBannerAdDisable,
    ShowInterstitialAd,
    ButtonForInterstitialClicked,
    SceneChanged
}